name: Safari Release Notes

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0,6,12,18 * * *"
  push:
  workflow_dispatch:

jobs:
  safari-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl https://developer.apple.com/tutorials/data/documentation/safari-release-notes.json | python -mjson.tool > data/safari-release-notes.json
      - run: |
          git config user.name "BalanceBot"
          git config user.email "hello@balance.io"
      - run: |
          git add -A
          git commit -m "Safari Release Notes Update: $(date -u)" || exit 0
          git push

  argent-web3-swift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl https://api.github.com/repos/argentlabs/web3.swift/commits | python -mjson.tool > data/argent-web3-swift.json
      - run: |
          git config user.name "BalanceBot"
          git config user.email "hello@balance.io"
      - run: |
          git add -A
          git commit -m "Argent web3.swift Update: $(date -u)" || exit 0
          git push
